
services:
    postgres:
      image: postgres:latest
      expose:
        - "5432:5432"
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres


    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 1234


